### ISSUE TITLE
QA_Computer Systems Organization_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#52] opened 2016-04-25 04:44 UTC
Defect Description :
In the home page of "Computer Systems Organization" Lab,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result :
In the home page of "Computer Systems Organization" Lab,when we click on the feedback link it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/system/Computer%20Systems%20Organization_08_Feedback_smk.org

Attachment:
![cso1](https://cloud.githubusercontent.com/assets/14869397/14779160/6276bfd0-0af4-11e6-8191-fa7057eb3293.png)

**Comment by sravanthimodepu** [comment] 2016-06-07 11:49
Issue is fixed now.

**Comment by BSravanthi** [comment] 2016-06-15 06:59
Closing the issue as the issue is fixed.

**Closed as completed by BSravanthi** 2016-06-15 06:59 UTC
Labels: 2018-Open, Release Number: Production, Developed By: VLEAD, Severity: S1, Category: Functionality, Status : Closed
